### ISSUE TITLE
Possible to release mRNA/cds sequences?

### ISSUE THREAD

**Issue by sz-1002** [djrichter/EukProt#2]
Hi EukProt Team!

Thank you very much for the great data source! 

I was wondering if it's possible that you also make the mRNA/cds sequences associated with the protein sequences available? I know that you've listed the sources in EukProt_included_data_sets.v03.2021_11_22.txt, but it is quite tedious to download the mRNA sequences as any of those that are not from standard places like NCBI or Ensembl have to be downloaded manually. I feel like many folks in the community would also be happy to see it.

Cheers!

**Comment by djrichter** [comment]
Hi!

I'm very glad to hear that EukProt has been useful for you.

Unfortunately, in the majority of cases, we did not download the mRNA sequences when building the database. We only downloaded the protein sequences, so we don't have the mRNA sequences in order to make them available.

You're not the first person to make this request, so we agree that it could be useful to the community! We're currently trying to prioritize requests and suggestions for the upcoming release of EukProt (v4; still without a release date), and there are so many good ideas that we will probably only have time to implement a subset of them.

Is there any chance we could convince you to volunteer to download the mRNA sequences, or even to organize a group of people to do it?

**Comment by sz-1002** [comment]
Hi @djrichter 

Ah, I see. Thank you for letting me know! Looking forward to EukProt v4.

About the mRNA sequences, I'm thinking I may need them in my analysis. No promise, but if I do end up downloading them (or part of them such as TCS or Opisthokonta), I would be happy to share.

**Comment by djrichter** [comment]
Great, if you do end up downloading them, please let us know!
